apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels: 
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql/mysql-server:8.0
          envFrom:
          - configMapRef:
              name: mysql-config
          - secretRef:
              name: mysql-user-creds
          ports:
            - name: mysql 
              containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-pv
      volumes:
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: mysql-pvc
