apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels: 
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      #      affinity:                                            
      #        podAffinity:                                       
      #          preferredDuringSchedulingIgnoredDuringExecution: 
      #          - weight: 100                                    
      #            podAffinityTerm:                               
      #              labelSelector:                               
      #                matchExpressions:                          
      #                - key: app                                 
      #                  operator: In                             
      #                  values:                                  
      #                  - wordpress                                  
      #              topologyKey: "kubernetes.io/hostname"        
      containers:
        - name: mysql
          image: mysql/mysql-server:8.0
          args: ["--skip-log-bin"]
          envFrom:
          - configMapRef:
              name: mysql-config
          - secretRef:
              name: mysql-user-creds
          ports:
            - name: mysql 
              containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-pv
      nodeSelector:
        k3s.io/hostname: "node06"
      volumes:
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: mysql-pvc
